/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "shazam.h"

bool_t
xdr_Buffer (XDR *xdrs, Buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->buffer, sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
