/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shazam.h"
#include <stdio.h>
#include <math.h>
#include <complex.h>
#include <stdlib.h>
#include <sndfile.h>

Buffer *get_music_buffer(char *name_file){
    SF_INFO info;
    SNDFILE *sf;
    sf = sf_open(name_file,SFM_READ,&info);
    if (sf == NULL){
        printf("Failed to open the file.\n");
        exit(-1);
    }
    Buffer *buffer = malloc(sizeof(Buffer));
    buffer->size = info.frames*info.channels;
    buffer->buffer = (float *) malloc(buffer->size*sizeof(float));
    sf_read_float(sf,buffer->buffer,buffer->size);
    sf_close(sf);
    return buffer;
}

char *prog_100(char *host, char *music_name)
{
	CLIENT *clnt;
	char * *result_1;
	Buffer  get_music_information_100_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");

	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	Buffer *music_buffer = get_music_buffer(music_name);
	result_1 = get_music_information_100(music_buffer, clnt);

	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG

	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return *result_1;

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char *music_name = argv[2];
	char *music_information = prog_100(host, music_name);
	//printf("%s\n", argv[2]);
exit (0);
}
