/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shazam.h"

char **
get_music_information_100_svc(Buffer *argp, struct svc_req *rqstp)
{
	static char * result = "FUNFANTE";
	printf("%s\n",result );

	return &result;
}
