/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "shazam.h"

bool_t
xdr_Buffer (XDR *xdrs, Buffer *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, 44100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
