/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "shazam.h"


char *prog_100(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	Buffer  get_music_information_100_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");

	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_music_information_100(&get_music_information_100_arg, clnt);
	printf("%s\n", *result_1);

	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG

	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return *result_1;

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char *music_information = prog_100(host);
	printf("%s\n", music_information);
exit (0);
}
