/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SHAZAM_H_RPCGEN
#define _SHAZAM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Buffer {
	int size;
	float buffer[44100];
};
typedef struct Buffer Buffer;

#define PROG 55555555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define get_music_information 1
extern  char ** get_music_information_100(Buffer *, CLIENT *);
extern  char ** get_music_information_100_svc(Buffer *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_music_information 1
extern  char ** get_music_information_100();
extern  char ** get_music_information_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Buffer (XDR *, Buffer*);

#else /* K&R C */
extern bool_t xdr_Buffer ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SHAZAM_H_RPCGEN */
